spring:
  application.name: gd_blog
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gd_blog?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # redis
  redis:
    host: 39.99.195.107
    port: 6379
    timeout: 5
    password: 123456
    pool:
      minIdle: 1
      maxIdle: 10
      maxWait: 3
      maxActive: 8

mybatis-plus:
  mapper-locations: classpath:mybatisPlus/mapper/*.xml
  #实体类扫描，多个实体类用,或;分隔
  type-aliases-package: com.gourddoll.entity
  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    #SIMPLE：该执行器类型不做特殊的事情，为每个语句的执行创建一个新的预处理语句,REUSE：该执行器类型会复用预处理语句,BATCH：该执行器类型会批量执行所有的更新语句
    default-executor-type: reuse

logging:
  level:
    root: info
    com:
      dao: debug